-- liquibase formatted sql
-- changeset itech:1743344293831-1
CREATE TABLE link_tags
(
    link_id BIGINT NOT NULL,
    tags    VARCHAR(255)
);

-- changeset itech:1743344293831-2
CREATE TABLE user_links
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    url          VARCHAR(2048)                           NOT NULL,
    filters      VARCHAR(255),
    last_updated TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_links PRIMARY KEY (id)
);

-- changeset itech:1743344293831-3
ALTER TABLE user_links
    ADD CONSTRAINT uc_81875aedfed417d38a46f70bc UNIQUE (user_id, url);

-- changeset itech:1743344293831-4
ALTER TABLE link_tags
    ADD CONSTRAINT fk_link_tags_on_link_data FOREIGN KEY (link_id) REFERENCES user_links (id);

